language: c
matrix:
  include:
  - env: TARGET="linux-clang"
    compiler: clang
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - env: TARGET="linux-gcc"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
  - env: TARGET="macos-clang"
    compiler: clang
    os: osx
    osx_image: xcode8.1
  - env: TARGET="macos-gcc"
    compiler: gcc
    os: osx
    osx_image: xcode8.1
  - env: TARGET="shared"
    compiler: gcc
    os: linux
    dist: trusty
    sudo: required
    group: edge
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then sudo apt-get update && sudo apt-mark hold oracle-java9-installer postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-client postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 postgresql-doc && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y && sudo apt-get install -y autopoint; fi
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew update && brew install gettext gnu-sed && brew link --force gettext; fi
install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then export SED="/usr/local/bin/gsed"; fi
  - if test ${TARGET} = "shared"; then ./syncsharedlibs.sh --use-head; fi
  - ./synclibs.sh --use-head && ./autogen.sh
  - if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
script:
  - if test ${TRAVIS_OS_NAME} = "linux"; then export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g"); fi
  - ./runtests.sh
after_success:
  - if test ${TARGET} = "linux-gcc"; then curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh; fi
